unzip /home/jobiols/Descargas/muk_account_accountant-11.0.1.0.0.zip -d .
unzip /home/jobiols/Descargas/muk_account_bank_statement_import_sheet-11.0.2.0.0.zip -d .
unzip /home/jobiols/Descargas/muk_attachment_lobject-11.0.2.0.2.zip -d .
unzip /home/jobiols/Descargas/muk_automation_extension-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_autovacuum-11.0.2.1.4.zip -d .
unzip /home/jobiols/Descargas/muk_converter-11.0.1.2.6.zip -d .
unzip /home/jobiols/Descargas/muk_dms-11.0.2.1.8.zip -d .
unzip /home/jobiols/Descargas/muk_dms_export-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_dms_field-11.0.2.0.6.zip -d .
unzip /home/jobiols/Descargas/muk_dms_file-11.0.2.0.10.zip -d .
unzip /home/jobiols/Descargas/muk_dms_lobject-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_dms_share-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_dms_thumbnails-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_fields_lobject-11.0.2.2.1.zip -d .
unzip /home/jobiols/Descargas/muk_hr_security-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_hr_utils-11.0.1.0.4.zip -d .
unzip /home/jobiols/Descargas/muk_models_groupby_hour-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_quality_docs-11.0.1.1.15.zip -d .
unzip /home/jobiols/Descargas/muk_quality_docs_dms-11.0.1.0.5.zip -d .
unzip /home/jobiols/Descargas/muk_quality_docs_hr-11.0.1.0.3.zip -d .
unzip /home/jobiols/Descargas/muk_security-11.0.1.1.8.zip -d .
unzip /home/jobiols/Descargas/muk_session_store-11.0.1.0.4.zip -d .
unzip /home/jobiols/Descargas/muk_web_client-11.0.2.0.2.zip -d .
unzip /home/jobiols/Descargas/muk_web_client_notification-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_export-11.0.1.0.7.zip -d .
unzip /home/jobiols/Descargas/muk_web_export_attachment-11.0.1.1.2.zip -d .
unzip /home/jobiols/Descargas/muk_web_fields_lobject-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_glyphicons-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview-11.0.2.1.4.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_attachment-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_audio-11.0.12.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_csv-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_image-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_lobject-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_mail-11.0.2.0.3.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_markdown-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_msoffice-11.0.2.0.2.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_rst-11.0.1.0.2.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_text-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_vector-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_preview_video-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_security-11.0.1.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_web_share-11.0.2.0.1.zip -d .
unzip /home/jobiols/Descargas/muk_website_customize_gradient-11.0.1.0.0.zip -d .
unzip /home/jobiols/Descargas/muk_website_navbar_transparent-11.0.1.0.2.zip -d .
unzip /home/jobiols/Descargas/muk_website_scroll_up-11.0.1.1.0.zip -d .
unzip /home/jobiols/Descargas/muk_website_snippet_grid-11.0.1.0.2.zip -d .
unzip /home/jobiols/Descargas/muk_website_snippet_particles-11.0.1.0.0.zip -d .
unzip /home/jobiols/Descargas/muk_web_utils-11.0.2.0.20.zip -d .


